[tools]
ruby = "3.2"

[tasks."rake:standard"]
description = "Run `rake standard`"
run = "rake standard"

[tasks."rake:standard:fix"]
description = "Run `rake standard:fix`"
run = "rake standard:fix"

[tasks."rake:spec"]
description = "Run `rake spec`"
run = "rake spec"

[tasks."rake:tasks"]
description = "Display all tasks with description"
run = "rake --tasks"

[tasks."rake:build"]
description = "Build omniauth-rocketchat-x.y.z.gem into the pkg directory"
run = "rake build"

[tasks."github:workflow:list"]
description = "List GitHub workflow runs"
run = "gh run list --workflow='main.yml'"

[tasks."github:workflow:run"]
depends_post = ["github:workflow:list"]
description = "Run the main workflow"
run = "gh workflow run .github/workflows/main.yml"
