name: Tests and Linting

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run StandardRb linting
        run: bundle exec standardrb
      - name: Run specs
        run: bundle exec rspec spec
